<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>
        
	promise对象

    </title>
    <link rel="shortcut icon" href="/public/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/page.css">
    <link rel="stylesheet" href="/public/css/monokai.min.css">
</head>

<body>
    <div id="headerWrapper" class="cf">
        <header id="header" class="cf">
            <div id="logo">
                <h1 class="logo">
					<a href="/"> 
	Learn ECMAScript6 the easy way
</a>
				</h1>
            </div>
        </header>
    </div>
    
<div id="pageWrapper">
	<div id="mainContent">
		<article class="post">
			<h1 id="promise-">Promise对象</h1>
<h2 id="promise-">Promise的含义</h2>
<p><code>Promise</code>在JavaScript语言早有实现，ES6将其写进了语言标准，统一了用法，原生提供了<code>Promise</code>对象。</p>
<p>所谓<code>Promise</code>，就是一个对象，用来传递异步操作的消息。它代表了某个未来才会知道结果的事件（通常是一个异步操作），并且这个事件提供统一的API，可供进一步处理。</p>
<p><code>Promise</code>对象有以下两个特点。</p>
<p>（1）对象的状态不受外界影响。<code>Promise</code>对象代表一个异步操作，有三种状态：<code>Pending</code>（进行中）、<code>Resolved</code>（已完成，又称Fulfilled）和<code>Rejected</code>（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是<code>Promise</code>这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。</p>
<p>（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。<code>Promise</code>对象的状态改变，只有两种可能：从<code>Pending</code>变为<code>Resolved</code>和从<code>Pending</code>变为<code>Rejected</code>。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果。就算改变已经发生了，你再对<code>Promise</code>对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。</p>
<p>有了<code>Promise</code>对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，<code>Promise</code>对象提供统一的接口，使得控制异步操作更加容易。</p>
<p><code>Promise</code>也有一些缺点。首先，无法取消<code>Promise</code>，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，<code>Promise</code>内部抛出的错误，不会反应到外部。第三，当处于<code>Pending</code>状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。</p>
<p>如果某些事件不断地反复发生，一般来说，使用stream模式是比部署<code>Promise</code>更好的选择。</p>
<h2 id="-">基本用法</h2>
<p>ES6规定，Promise对象是一个构造函数，用来生成Promise实例。</p>
<p>下面代码创造了一个Promise实例。</p>
<pre><code class="lang-javascript">var promise = new Promise(function(resolve, reject) {
  // ... some code

  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
</code></pre>
<p>Promise构造函数接受一个函数作为参数，该函数的两个参数分别是<code>resolve</code>和<code>reject</code>。它们是两个函数，由JavaScript引擎提供，不用自己部署。</p>
<p><code>resolve</code>函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从Pending变为Resolved），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；<code>reject</code>函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从Pending变为Rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。</p>
<p>Promise实例生成以后，可以用then方法分别指定Resolved状态和Reject状态的回调函数。</p>
<pre><code class="lang-javascript">promise.then(function(value) {
  // success
}, function(value) {
  // failure
});
</code></pre>
<p><code>then</code>方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为Resolved时调用，第二个回调函数是Promise对象的状态变为Reject时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。</p>
<p>下面是一个Promise对象的简单例子。</p>
<pre><code class="lang-javascript">function timeout(ms) {
  return new Promise((resolve, reject) =&gt; {
    setTimeout(resolve, ms, &#39;done&#39;);
  });
}

timeout(100).then((value) =&gt; {
  console.log(value);
});
</code></pre>
<p>上面代码中，<code>timeout</code>方法返回一个Promise实例，表示一段时间以后才会发生的结果。过了指定的时间（<code>ms</code>参数）以后，Promise实例的状态变为Resolved，就会触发<code>then</code>方法绑定的回调函数。</p>
<p>下面是异步加载图片的例子。</p>
<pre><code class="lang-javascript">function loadImageAsync(url) {
  return new Promise(function(resolve, reject) {
    var image = new Image();

    image.onload = function() {
      resolve(image);
    };

    image.onerror = function() {
      reject(new Error(&#39;Could not load image at &#39; + url));
    };

    image.src = url;
  });
}
</code></pre>
<p>下面是一个用Promise对象实现的Ajax操作的例子。</p>
<pre><code class="lang-javascript">var getJSON = function(url) {
  var promise = new Promise(function(resolve, reject){
    var client = new XMLHttpRequest();
    client.open(&quot;GET&quot;, url);
    client.onreadystatechange = handler;
    client.responseType = &quot;json&quot;;
    client.setRequestHeader(&quot;Accept&quot;, &quot;application/json&quot;);
    client.send();

    function handler() {
      if ( this.readyState !== 4 ) {
        return;
      }
      if (this.status === 200) {
        resolve(this.response);
      } else {
        reject(new Error(this.statusText));
      }
    };
  });

  return promise;
};

getJSON(&quot;/posts.json&quot;).then(function(json) {
  console.log(&#39;Contents: &#39; + json);
}, function(error) {
  console.error(&#39;出错了&#39;, error);
});
</code></pre>
<p>上面代码中，<code>getJSON</code>是对XMLHttpRequest对象的封装，用于发出一个针对JSON数据的HTTP请求，并且返回一个Promise对象。需要注意的是，在<code>getJSON</code>内部，<code>resolve</code>函数和<code>reject</code>函数调用时，都带有参数。</p>
<p>如果调用<code>resolve</code>函数和<code>reject</code>函数时带有参数，那么它们的参数会被传递给回调函数。<code>reject</code>函数的参数通常是Error对象的实例，表示抛出的错误；<code>resolve</code>函数的参数除了正常的值以外，还可能是另一个Promise实例，表示异步操作的结果有可能是一个值，也有可能是另一个异步操作，比如像下面这样。</p>
<pre><code class="lang-javascript">var p1 = new Promise(function(resolve, reject){
  // ...
});

var p2 = new Promise(function(resolve, reject){
  // ...
  resolve(p1);
})
</code></pre>
<p>上面代码中，<code>p1</code>和<code>p2</code>都是Promise的实例，但是<code>p2</code>的<code>resolve</code>方法将<code>p1</code>作为参数，即一个异步操作的结果是返回另一个异步操作。</p>
<p>注意，这时<code>p1</code>的状态就会传递给<code>p2</code>，也就是说，<code>p1</code>的状态决定了<code>p2</code>的状态。如果<code>p1</code>的状态是<code>Pending</code>，那么<code>p2</code>的回调函数就会等待<code>p1</code>的状态改变；如果<code>p1</code>的状态已经是<code>Resolved</code>或者<code>Rejected</code>，那么<code>p2</code>的回调函数将会立刻执行。</p>
<pre><code class="lang-javascript">var p1 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; reject(new Error(&#39;fail&#39;)), 3000)
})
var p2 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; resolve(p1), 1000)
})
p2.then(result =&gt; console.log(result))
p2.catch(error =&gt; console.log(error))
// Error: fail
</code></pre>
<p>上面代码中，<code>p1</code>是一个Promise，3秒之后变为<code>rejected</code>。<code>p2</code>的状态由<code>p1</code>决定，1秒之后，<code>p2</code>调用<code>resolve</code>方法，但是此时<code>p1</code>的状态还没有改变，因此<code>p2</code>的状态也不会变。又过了2秒，<code>p1</code>变为<code>rejected</code>，<code>p2</code>也跟着变为<code>rejected</code>。</p>
<h2 id="promise-prototype-then-">Promise.prototype.then()</h2>
<p>Promise实例具有<code>then</code>方法，也就是说，<code>then</code>方法是定义在原型对象Promise.prototype上的。它的作用是为Promise实例添加状态改变时的回调函数。前面说过，<code>then</code>方法的第一个参数是Resolved状态的回调函数，第二个参数（可选）是Rejected状态的回调函数。</p>
<p><code>then</code>方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即<code>then</code>方法后面再调用另一个<code>then</code>方法。</p>
<pre><code class="lang-javascript">getJSON(&quot;/posts.json&quot;).then(function(json) {
  return json.post;
}).then(function(post) {
  // ...
});
</code></pre>
<p>上面的代码使用<code>then</code>方法，依次指定了两个回调函数。第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数。</p>
<p>采用链式的<code>then</code>，可以指定一组按照次序调用的回调函数。这时，前一个回调函数，有可能返回的还是一个Promise对象（即有异步操作），这时后一个回调函数，就会等待该Promise对象的状态发生变化，才会被调用。</p>
<pre><code class="lang-javascript">getJSON(&quot;/post/1.json&quot;).then(function(post) {
  return getJSON(post.commentURL);
}).then(function funcA(comments) {
  console.log(&quot;Resolved: &quot;, comments);
}, function funcB(err){
  console.log(&quot;Rejected: &quot;, err);
});
</code></pre>
<p>上面代码中，第一个<code>then</code>方法指定的回调函数，返回的是另一个Promise对象。这时，第二个<code>then</code>方法指定的回调函数，就会等待这个新的Promise对象状态发生变化。如果变为Resolved，就调用<code>funcA</code>，如果状态变为Rejected，就调用<code>funcB</code>。</p>
<p>如果采用箭头函数，上面的代码可以写得更简洁。</p>
<pre><code class="lang-javascript">getJSON(&quot;/post/1.json&quot;).then(
  post =&gt; getJSON(post.commentURL)
).then(
  comments =&gt; console.log(&quot;Resolved: &quot;, comments),
  err =&gt; console.log(&quot;Rejected: &quot;, err)
);
</code></pre>
<h2 id="promise-prototype-catch-">Promise.prototype.catch()</h2>
<p>Promise.prototype.catch方法是<code>.then(null, rejection)</code>的别名，用于指定发生错误时的回调函数。</p>
<pre><code class="lang-javascript">getJSON(&quot;/posts.json&quot;).then(function(posts) {
  // ...
}).catch(function(error) {
  // 处理前一个回调函数运行时发生的错误
  console.log(&#39;发生错误！&#39;, error);
});
</code></pre>
<p>上面代码中，<code>getJSON</code>方法返回一个Promise对象，如果该对象状态变为Resolved，则会调用<code>then</code>方法指定的回调函数；如果异步操作抛出错误，状态就会变为Rejected，就会调用<code>catch</code>方法指定的回调函数，处理这个错误。</p>
<pre><code class="lang-javascript">p.then((val) =&gt; console.log(&quot;fulfilled:&quot;, val))
  .catch((err) =&gt; console.log(&quot;rejected:&quot;, err));

// 等同于

p.then((val) =&gt; console.log(fulfilled:&quot;, val))
  .then(null, (err) =&gt; console.log(&quot;rejected:&quot;, err));
</code></pre>
<p>下面是一个例子。</p>
<pre><code class="lang-javascript">var promise = new Promise(function(resolve, reject) {
  throw new Error(&#39;test&#39;)
});
promise.catch(function(error) { console.log(error) });
// Error: test
</code></pre>
<p>上面代码中，Promise抛出一个错误，就被<code>catch</code>方法指定的回调函数捕获。</p>
<p>如果Promise状态已经变成resolved，再抛出错误是无效的。</p>
<pre><code class="lang-javascript">var promise = new Promise(function(resolve, reject) {
  resolve(&quot;ok&quot;);
  throw new Error(&#39;test&#39;);
});
promise
  .then(function(value) { console.log(value) })
  .catch(function(error) { console.log(error) });
// ok
</code></pre>
<p>上面代码中，Promise在<code>resolve</code>语句后面，再抛出错误，不会被捕获，等于没有抛出。</p>
<p>Promise对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个<code>catch</code>语句捕获。</p>
<pre><code class="lang-javascript">getJSON(&quot;/post/1.json&quot;).then(function(post) {
  return getJSON(post.commentURL);
}).then(function(comments) {
  // some code
}).catch(function(error) {
  // 处理前面三个Promise产生的错误
});
</code></pre>
<p>上面代码中，一共有三个Promise对象：一个由<code>getJSON</code>产生，两个由<code>then</code>产生。它们之中任何一个抛出的错误，都会被最后一个<code>catch</code>捕获。</p>
<p>一般来说，不要在<code>then</code>方法里面定义Reject状态的回调函数（即<code>then</code>的第二个参数），总是使用<code>catch</code>方法。</p>
<pre><code class="lang-javascript">// bad
promise
  .then(function(data) {
    // success
  }, function(err) {
    // error
  });

// good
promise
  .then(function(data) { //cb
    // success
  })
  .catch(function(err) {
    // error
  });
</code></pre>
<p>上面代码中，第二种写法要好于第一种写法，理由是前者更接近同步的写法（try/catch）。</p>
<p>跟传统的try/catch代码块不同的是，如果没有使用<code>catch</code>方法指定错误处理的回调函数，Promise对象抛出的错误不会传递到外层代码，即不会有任何反应。</p>
<pre><code class="lang-javascript">var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};

someAsyncThing().then(function() {
  console.log(&#39;everything is great&#39;);
});
</code></pre>
<p>上面代码中，<code>someAsyncThing</code>函数产生的Promise对象会报错，但是由于没有指定<code>catch</code>方法，这个错误不会被捕获，也不会传递到外层代码，导致运行后没有任何输出。</p>
<pre><code class="lang-javascript">var promise = new Promise(function(resolve, reject) {
  resolve(&quot;ok&quot;);
  setTimeout(function() { throw new Error(&#39;test&#39;) }, 0)
});
promise.then(function(value) { console.log(value) });
// ok
// Uncaught Error: test
</code></pre>
<p>上面代码中，Promise指定在下一轮“事件循环”再抛出错误，结果由于没有指定使用try...catch语句，就冒泡到最外层，成了未捕获的错误。因为此时，Promise的函数体已经运行结束了，所以这个错误是在Promise函数体外抛出的。</p>
<p>Node.js有一个<code>unhandledRejection</code>事件，专门监听未捕获的<code>reject</code>错误。</p>
<pre><code class="lang-javascript">process.on(&#39;unhandledRejection&#39;, function (err, p) {
  console.error(err.stack)
});
</code></pre>
<p>上面代码中，<code>unhandledRejection</code>事件的监听函数有两个参数，第一个是错误对象，第二个是报错的Promise实例，它可以用来了解发生错误的环境信息。。</p>
<p>需要注意的是，<code>catch</code>方法返回的还是一个Promise对象，因此后面还可以接着调用<code>then</code>方法。</p>
<pre><code class="lang-javascript">var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};

someAsyncThing()
.catch(function(error) {
  console.log(&#39;oh no&#39;, error);
})
.then(function() {
  console.log(&#39;carry on&#39;);
});
// oh no [ReferenceError: x is not defined]
// carry on
</code></pre>
<p>上面代码运行完<code>catch</code>方法指定的回调函数，会接着运行后面那个<code>then</code>方法指定的回调函数。如果没有报错，则会跳过<code>catch</code>方法。</p>
<pre><code class="lang-javascript">Promise.resolve()
.catch(function(error) {
  console.log(&#39;oh no&#39;, error);
})
.then(function() {
  console.log(&#39;carry on&#39;);
});
// carry on
</code></pre>
<p>上面的代码因为没有报错，跳过了<code>catch</code>方法，直接执行后面的<code>then</code>方法。此时，要是<code>then</code>方法里面报错，就与前面的<code>catch</code>无关了。</p>
<p><code>catch</code>方法之中，还能再抛出错误。</p>
<pre><code class="lang-javascript">var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};

someAsyncThing().then(function() {
  return someOtherAsyncThing();
}).catch(function(error) {
  console.log(&#39;oh no&#39;, error);
  // 下面一行会报错，因为y没有声明
  y + 2;
}).then(function() {
  console.log(&#39;carry on&#39;);
});
// oh no [ReferenceError: x is not defined]
</code></pre>
<p>上面代码中，<code>catch</code>方法抛出一个错误，因为后面没有别的<code>catch</code>方法了，导致这个错误不会被捕获，也不会传递到外层。如果改写一下，结果就不一样了。</p>
<pre><code class="lang-javascript">someAsyncThing().then(function() {
  return someOtherAsyncThing();
}).catch(function(error) {
  console.log(&#39;oh no&#39;, error);
  // 下面一行会报错，因为y没有声明
  y + 2;
}).catch(function(error) {
  console.log(&#39;carry on&#39;, error);
});
// oh no [ReferenceError: x is not defined]
// carry on [ReferenceError: y is not defined]
</code></pre>
<p>上面代码中，第二个<code>catch</code>方法用来捕获，前一个<code>catch</code>方法抛出的错误。</p>
<h2 id="promise-all-">Promise.all()</h2>
<p><code>Promise.all</code>方法用于将多个Promise实例，包装成一个新的Promise实例。</p>
<pre><code class="lang-javascript">var p = Promise.all([p1,p2,p3]);
</code></pre>
<p>上面代码中，<code>Promise.all</code>方法接受一个数组作为参数，<code>p1</code>、<code>p2</code>、<code>p3</code>都是Promise对象的实例，如果不是，就会先调用下面讲到的<code>Promise.resolve</code>方法，将参数转为Promise实例，再进一步处理。（<code>Promise.all</code>方法的参数不一定是数组，但是必须具有iterator接口，且返回的每个成员都是Promise实例。）</p>
<p><code>p</code>的状态由<code>p1</code>、<code>p2</code>、<code>p3</code>决定，分成两种情况。</p>
<p>（1）只有<code>p1</code>、<code>p2</code>、<code>p3</code>的状态都变成<code>fulfilled</code>，<code>p</code>的状态才会变成<code>fulfilled</code>，此时<code>p1</code>、<code>p2</code>、<code>p3</code>的返回值组成一个数组，传递给<code>p</code>的回调函数。</p>
<p>（2）只要<code>p1</code>、<code>p2</code>、<code>p3</code>之中有一个被<code>rejected</code>，<code>p</code>的状态就变成<code>rejected</code>，此时第一个被<code>reject</code>的实例的返回值，会传递给<code>p</code>的回调函数。</p>
<p>下面是一个具体的例子。</p>
<pre><code class="lang-javascript">// 生成一个Promise对象的数组
var promises = [2, 3, 5, 7, 11, 13].map(function(id){
  return getJSON(&quot;/post/&quot; + id + &quot;.json&quot;);
});

Promise.all(promises).then(function(posts) {
  // ...
}).catch(function(reason){
  // ...
});
</code></pre>
<h2 id="promise-race-">Promise.race()</h2>
<p><code>Promise.race</code>方法同样是将多个Promise实例，包装成一个新的Promise实例。</p>
<pre><code class="lang-javascript">var p = Promise.race([p1,p2,p3]);
</code></pre>
<p>上面代码中，只要<code>p1</code>、<code>p2</code>、<code>p3</code>之中有一个实例率先改变状态，<code>p</code>的状态就跟着改变。那个率先改变的Promise实例的返回值，就传递给<code>p</code>的回调函数。</p>
<p><code>Promise.race</code>方法的参数与<code>Promise.all</code>方法一样，如果不是Promise实例，就会先调用下面讲到的<code>Promise.resolve</code>方法，将参数转为Promise实例，再进一步处理。</p>
<p>下面是一个例子，如果指定时间内没有获得结果，就将Promise的状态变为<code>reject</code>，否则变为<code>resolve</code>。</p>
<pre><code class="lang-javascript">var p = Promise.race([
  fetch(&#39;/resource-that-may-take-a-while&#39;),
  new Promise(function (resolve, reject) {
    setTimeout(() =&gt; reject(new Error(&#39;request timeout&#39;)), 5000)
  })
])
p.then(response =&gt; console.log(response))
p.catch(error =&gt; console.log(error))
</code></pre>
<p>上面代码中，如果5秒之内<code>fetch</code>方法无法返回结果，变量<code>p</code>的状态就会变为<code>rejected</code>，从而触发<code>catch</code>方法指定的回调函数。</p>
<h2 id="promise-resolve-">Promise.resolve()</h2>
<p>有时需要将现有对象转为Promise对象，Promise.resolve方法就起到这个作用。</p>
<pre><code class="lang-javascript">var jsPromise = Promise.resolve($.ajax(&#39;/whatever.json&#39;));
</code></pre>
<p>上面代码将jQuery生成的<code>deferred</code>对象，转为一个新的Promise对象。</p>
<p><code>Promise.resolve</code>等价于下面的写法。</p>
<pre><code class="lang-javascript">Promise.resolve(&#39;foo&#39;)
// 等价于
new Promise(resolve =&gt; resolve(&#39;foo&#39;))
</code></pre>
<p>如果Promise.resolve方法的参数，不是具有then方法的对象（又称thenable对象），则返回一个新的Promise对象，且它的状态为Resolved。</p>
<pre><code class="lang-javascript">var p = Promise.resolve(&#39;Hello&#39;);

p.then(function (s){
  console.log(s)
});
// Hello
</code></pre>
<p>上面代码生成一个新的Promise对象的实例p。由于字符串Hello不属于异步操作（判断方法是它不是具有then方法的对象），返回Promise实例的状态从一生成就是Resolved，所以回调函数会立即执行。Promise.resolve方法的参数，会同时传给回调函数。</p>
<p>Promise.resolve方法允许调用时不带参数。所以，如果希望得到一个Promise对象，比较方便的方法就是直接调用Promise.resolve方法。</p>
<pre><code class="lang-javascript">var p = Promise.resolve();

p.then(function () {
  // ...
});
</code></pre>
<p>上面代码的变量p就是一个Promise对象。</p>
<p>如果Promise.resolve方法的参数是一个Promise实例，则会被原封不动地返回。</p>
<h2 id="promise-reject-">Promise.reject()</h2>
<p><code>Promise.reject(reason)</code>方法也会返回一个新的Promise实例，该实例的状态为<code>rejected</code>。<code>Promise.reject</code>方法的参数<code>reason</code>，会被传递给实例的回调函数。</p>
<pre><code class="lang-javascript">var p = Promise.reject(&#39;出错了&#39;);
// 等同于
var p = new Promise((resolve, reject) =&gt; reject(&#39;foo&#39;))

p.then(null, function (s){
  console.log(s)
});
// 出错了
</code></pre>
<p>上面代码生成一个Promise对象的实例<code>p</code>，状态为<code>rejected</code>，回调函数会立即执行。</p>
<h2 id="-">两个有用的附加方法</h2>
<p>ES6的Promise API提供的方法不是很多，有些有用的方法可以自己部署。下面介绍如何部署两个不在ES6之中、但很有用的方法。</p>
<h3 id="done-">done()</h3>
<p>Promise对象的回调链，不管以<code>then</code>方法或<code>catch</code>方法结尾，要是最后一个方法抛出错误，都有可能无法捕捉到（因为Promise内部的错误不会冒泡到全局）。因此，我们可以提供一个<code>done</code>方法，总是处于回调链的尾端，保证抛出任何可能出现的错误。</p>
<pre><code class="lang-javascript">asyncFunc()
  .then(f1)
  .catch(r1)
  .then(f2)
  .done();
</code></pre>
<p>它的实现代码相当简单。</p>
<pre><code class="lang-javascript">Promise.prototype.done = function (onFulfilled, onRejected) {
  this.then(onFulfilled, onRejected)
    .catch(function (reason) {
      // 抛出一个全局错误
      setTimeout(() =&gt; { throw reason }, 0);
    });
};
</code></pre>
<p>从上面代码可见，<code>done</code>方法的使用，可以像<code>then</code>方法那样用，提供<code>Fulfilled</code>和<code>Rejected</code>状态的回调函数，也可以不提供任何参数。但不管怎样，<code>done</code>都会捕捉到任何可能出现的错误，并向全局抛出。</p>
<h3 id="finally-">finally()</h3>
<p><code>finally</code>方法用于指定不管Promise对象最后状态如何，都会执行的操作。它与<code>done</code>方法的最大区别，它接受一个普通的回调函数作为参数，该函数不管怎样都必须执行。</p>
<p>下面是一个例子，服务器使用Promise处理请求，然后使用<code>finally</code>方法关掉服务器。</p>
<pre><code class="lang-javascript">server.listen(0)
  .then(function () {
    // run test
  })
  .finally(server.stop);
</code></pre>
<p>它的实现也很简单。</p>
<pre><code class="lang-javascript">Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  =&gt; P.resolve(callback()).then(() =&gt; value),
    reason =&gt; P.resolve(callback()).then(() =&gt; { throw reason })
  );
};
</code></pre>
<p>上面代码中，不管前面的Promise是<code>fulfilled</code>还是<code>rejected</code>，都会执行回调函数<code>callback</code>。</p>
<h2 id="-">应用</h2>
<h3 id="-">加载图片</h3>
<p>我们可以将图片的加载写成一个<code>Promise</code>，一旦加载完成，<code>Promise</code>的状态就发生变化。</p>
<pre><code class="lang-javascript">const preloadImage = function (path) {
  return new Promise(function (resolve, reject) {
    var image = new Image();
    image.onload  = resolve;
    image.onerror = reject;
    image.src = path;
  });
};
</code></pre>
<h3 id="generator-promise-">Generator函数与Promise的结合</h3>
<p>使用Generator函数管理流程，遇到异步操作的时候，通常返回一个<code>Promise</code>对象。</p>
<pre><code class="lang-javascript">function getFoo () {
  return new Promise(function (resolve, reject){
    resolve(&#39;foo&#39;);
  });
}

var g = function* () {
  try {
    var foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log(e);
  }
};

function run (generator) {
  var it = generator();

  function go(result) {
    if (result.done) return result.value;

    return result.value.then(function (value) {
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
  }

  go(it.next());
}

run(g);
</code></pre>
<p>上面代码的Generator函数<code>g</code>之中，有一个异步操作<code>getFoo</code>，它返回的就是一个<code>Promise</code>对象。函数<code>run</code>用来处理这个<code>Promise</code>对象，并调用下一个<code>next</code>方法。</p>
<h2 id="async-">async函数</h2>
<p>async函数与Promise、Generator函数一样，是用来取代回调函数、解决异步操作的一种方法。它本质上是Generator函数的语法糖。async函数并不属于ES6，而是被列入了ES7，但是traceur、Babel.js、regenerator等转码器已经支持这个功能，转码后立刻就能使用。</p>
<p>async函数的详细介绍，请看《异步操作》一章。</p>

		</article>
	</div>
</div>

    <footer id="footer">
        <i id="upToTop"></i>
        <p>
            <span>作者-阮一峰：<a href="http://es6.ruanyifeng.com/">http://es6.ruanyifeng.com/</a></span>|联系方式 <span>|</span> <a href="javascript:void(0);">yangxiaofuPL@163.com</a>
        </p>
    </footer>
    <script src="/public/js/jquery-2.1.4.min.js"></script>
    <script src="/public/js/highlight.min.js"></script>
    <script src="/public/js/codepretty.js"></script>
</body>

</html>
